### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by Vonr** [auoeke/limitless#2]
Make options for the changes the mod makes to the game so that some can be switched off.
A per-enchant/potion limit in the config would also be really nice and would help to make the mod balanceable
Maybe an option to increase enchantability based on blocks that give enchanting power (e.g. bookshelves) and another config to add more of such blocks.

**Comment by user11681** [comment]
Should be simple to implement; I will do it when I have the time for it. Also, this mod should not do anything to potions besides preventing Minecraft from truncating their levels (that can be acquired only by commands like `/effect` and `/give`).
