### ISSUE TITLE
[Suggestion] Add Combability to Actually Unbreaking

### ISSUE THREAD

**Issue by kalinzange** [auoeke/limitless#46]
If possible to add compatibility of [Actually Unbreaking Mod](https://www.curseforge.com/minecraft/mc-mods/actually-unbreaking-fabric)

**Comment by auoeke** [comment]
Specifically what do you mean by "compatibility"?

**Comment by kalinzange** [comment]
> Specifically what do you mean by "compatibility"?

The [Actually Unbreaking Mod](https://www.curseforge.com/minecraft/mc-mods/actually-unbreaking-fabric) makes the Unbreaking level 1 enchantment actually unbreaking (Doesn't consumes tool durability as it says by the name. 

When adding this mod even the unbreaking level 1 can be increased to 2, 3, 4, 5. Even when I specify on the [Actually Unbreaking Mod](https://www.curseforge.com/minecraft/mc-mods/actually-unbreaking-fabric) to make the tool/book unbreakable when reaches to max level only it still increases the level.

I've afterwards edited your mod config to make the max level 5 and whenever I reach level 5 I can't make the tool/book unbreakable 

If you didn't understand I can record a video and show what I meant.

**Comment by auoeke** [comment]
I believe that I understand. I will look into it.

**Comment by auoeke** [comment]
The latest (1.17-0.2.2; alpha) version of Actually Unbreaking is compatible with limitless.
