### ISSUE TITLE
Crash with Fabric API 0.40.0

### ISSUE THREAD

**Issue by MysteriousDownloader** [auoeke/limitless#51]
I don't know if I'm wrong or something but It just instantly crashes with Fabric API 0.40.0. No Crash Logs. But when I removed your Mod it worked fine. Then I Re Added Limitless and Used API 0.39.2 it works. It also just Insta Crashes with Levelz Mod regardless of API version. Error: Game Crashed - An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 0.

(First time at submitting Issues.)

**Comment by auoeke** [comment]
limitless 1.5.3 works with Fabric API 0.40.0 for me. I need to see `logs/latest.log` in your Minecraft directory to know what is wrong.
I can fix the crash with LevelZ though.

**Comment by MysteriousDownloader** [comment]
this is the latest log.

[14:39:03] [main/INFO]: Loading for game Minecraft 1.17.1
[14:39:03] [ForkJoinPool-1-worker-9/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[14:39:04] [ForkJoinPool-1-worker-13/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[14:39:04] [ForkJoinPool-1-worker-13/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[14:39:04] [ForkJoinPool-1-worker-7/WARN]: Non-Fabric mod JAR at "C:\Users\User\AppData\Roaming\.minecraft\mods\illuminations-uninstaller.jar", ignoring
[14:39:05] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[14:39:05] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+8d89ed5432, 0.3.0+a02b4463d5, 0.3.0+a02b44633d, 0.3.0+a02b446318, 0.3.0+a02b4463a0
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afa13, also found 0.3.2+92519afad5, 0.3.2+92519afa18
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.4+cbda931818, also found 1.0.4+a02b44633d
 - Mod 'Clear Despawn' (cleardespawn) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.
 - Conflicting versions found for fabric-object-builder-api-v1: used 1.10.9+b7ab6121d5, also found 1.10.9+b7ab612118, 1.10.9+cbda931818
 - Conflicting versions found for fabric-rendering-data-attachment-v1: used 0.1.5+a02b446313, also found 0.1.5+a02b446318
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b4463d5, also found 1.4.4+a02b44633d, 1.4.4+a02b446318
 - Conflicting versions found for fabric-command-api-v1: used 1.1.3+5ab9934c68, also found 1.1.3+5ab9934c18
 - Conflicting versions found for fabric-tag-extensions-v0: used 1.2.1+b06cb95b68, also found 1.2.1+b06cb95b18
 - Conflicting versions found for fabric-tool-attribute-api-v1: used 1.2.12+b7ab6121d5, also found 1.2.12+b7ab61213d, 1.2.12+b7ab612118
 - Conflicting versions found for fabric-renderer-api-v1: used 0.4.4+cbda931818, also found 0.4.4+5f02c96918
 - Conflicting versions found for fabric-rendering-fluids-v1: used 0.1.13+a02b446318, also found 0.1.13+a02b446313
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+198a96213d, also found 1.0.4+cbda931818
 - Conflicting versions found for fabric-item-api-v1: used 1.2.4+a02b4463d5, also found 1.2.4+a02b44633d, 1.2.4+cbda931818, 1.2.4+a02b446318
[14:39:05] [main/INFO]: [FabricLoader] Loading 361 mods:
	- adapaxels@1.2.1+1.17.1
	- additionaladditions@2.1.2
	- additionalbars@2.1.1
	- advanced_runtime_resource_pack@0.2.9
	- advancementplaques@1.4.0
	- advancements-enlarger@0.2.4
	- adventurez@1.2.11
	- amecsapi@1.1.5+mc21w16a
	- appletreesrev@2.3
	- aqupdcaracal@1.17-1.3.11
	- aqupdgrizzly@1.17-1.2.0
	- arcanus@1.7
	- architects_palette@1.2
	- architectury@2.5.27
	- artifality@0.3.5
	- assembly@21w06a-1.0.0
	- attributefix@1.0.3
	- awokenworld@1.0.1
	- axolotlitemfix@1.1.2
	- backslot@1.2.0
	- backslotaddon@1.0.6
	- barrenisles@1.0.7
	- bclib@0.3.1
	- beaconoverhaul@1.4.1+1.17
	- betterend@0.11.0-pre
	- bettermineshafts@1.17-1.0.1
	- betternether@5.1.3
	- bettersodiumvideosettingsbutton@2.0.1
	- betterstrongholds@1.17-1.1.1
	- betterthanmending@1.3.0
	- betterthirdperson@1.5.0
	- bewitchment@1.17-5
	- biomeinfo@1.17-7
	- blue_endless_jankson@1.2.1
	- caelus@0.0.17-1.17
	- cardinal-components@3.1.1
	- cardinal-components-base@3.1.1
	- cardinal-components-block@3.1.1
	- cardinal-components-chunk@3.1.1
	- cardinal-components-entity@3.1.1
	- cardinal-components-item@3.1.1
	- cardinal-components-level@3.1.1
	- cardinal-components-scoreboard@3.1.1
	- cardinal-components-util@3.1.1
	- cardinal-components-world@3.1.1
	- carrier@1.8.0
	- caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld@1.3
	- charm@3.3.2
	- charmonium@3.3.0
	- cherishedworlds@2.0.1-1.17.1
	- cleancut@1.17-4.0-fabric
	- clear-skies@1.5.70
	- cleardespawn@1.17.1-fabric0.36.1-1.1.1
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.38
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- clumps@fabric-1.17.1-7.0.5
	- colytra@2.0.0-1.17
	- com_electronwill_night-config_core@3.6.3
	- com_electronwill_night-config_toml@3.6.3
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- comforts@0.0.6-1.17.1
	- conjuring@1.0.7
	- controlling@1.1.2
	- couplings@1.5.0+1.17
	- cozy_camping@1.0.0-1.17
	- croptopia@1.6.1
	- croptosis@1.1.3
	- crowdin-translate@1.3+1.17
	- customportalapi@0.0.1-beta41-1.17
	- dark-enchanting@0.4.1-1.17.1
	- darkpaintings@4.0.2
	- dashloader@2.0
	- dataattributes@1.0.2
	- dawn@2.0.6
	- deepslatecutting@1.2.0
	- detailab@2.4.2+1.17.1-fabric
	- diggusmaximus@1.4.5-1.17
	- disable_custom_worlds_advice@1.3
	- dragonloot@1.0.9
	- drinkbeer@2.1
	- dual_riders@1.0.5
	- dualwielding@1.0.6
	- dungeons_arise@2.1.47-fabric
	- dynamicfps@2.0.5
	- dynmus@1.3.1
	- earthtojavamobs@1.7.3+1.17
	- eldritch_mobs@1.9.2
	- elytratrinket@2.0.1-1.17
	- emerald_tools@1.2.27
	- enchantment_lore@1.2.1+MC1.17.1
	- endrem@4.1.0
	- enhanced_attack_indicator@1.0.2+1.17
	- enhanced_mushrooms@1.0.5
	- enhancedcelestials@2.0.4
	- fabric@0.40.0+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c68
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+a02b4463d5
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-lifecycle-events-v1@1.4.4+a02b4463d5
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+b7ab6121d5
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.2+fc40aa9d18
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.3+fc40aa9d18
	- fabric-rendering-v1@1.8.1+fc40aa9d18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b68
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5
	- fabric-transfer-api-v1@1.3.0+fc40aa9d18
	- fabric-tree-chopper@0.7.2
	- fabricasmtools@0.4.0
	- fabricloader@0.11.6
	- fallingleaves@1.7.3+1.17.1
	- fancymenu@2.2.2
	- fermion@2.11.241
	- fermion-modkeys@1.10.241
	- ferritecore@3.0.3
	- fiber@0.23.0-2
	- fiber2cloth@3.2.0
	- flesh2leather@1.0.2
	- flight_rings@1.6
	- flintytools@1.0.0
	- flytre-lib-base@1.2.0
	- flytre-lib-compat@1.0.0
	- flytre-lib-config@1.1.0
	- flytre-lib-event@1.0.1
	- flytre-lib-gui@1.0.0
	- flytre-lib-storage@2.3.1
	- flytre_lib@1.3.7
	- forgottenrecipes@1.0.2
	- gateofbabylon@1.5.0-1.17
	- gbfabrictools@1.3.4+1.17
	- geckolib3@3.0.13
	- gobber2@2.4.43
	- gottaclimbfast@1.17-3.0-fabric
	- grass_pass@1.0.0
	- graveyard@1.0
	- grindenchantments@1.2.1+1.17.1
	- haema@1.7.6+1.17
	- harvest_scythes@2.0.6
	- healthoverlay@4.0.1
	- hologram-api@0.2.1+1.17.1
	- horizontalpanes@1.1.5
	- horsestatsvanilla@4.1.8
	- icarus@1.3
	- illuminations@1.7
	- impaled@1.0.1
	- impersonate@2.3.3
	- inmis@2.3.1-1.17
	- interactic@0.1.5-1.17
	- inventoryhud@3.4.0
	- io_activej_activej-codegen@4.3
	- io_activej_activej-serializer@4.3
	- ironchests@1.4.2
	- jankson@3.0.1+j1.2.0
	- java@16
	- kanos_config@0.1.4+1.14.4-1.17.1
	- kbootstrap@0.1.1
	- kirin@1.9.1
	- konkrete@1.2.3
	- krypton@0.1.4
	- kubejs@1605.3.10-build.9999
	- kyrptconfig@1.1.10-1.17
	- lacrimis@2.1.3+1.17.1
	- levelz@1.0.5
	- libcd@3.0.3+1.16.3
	- libgui@4.1.7+1.17.1
	- libninepatch@1.1.0
	- limitless@1.5.4
	- lithium@0.7.4
	- lovely_snails@1.0.3+1.17
	- magicfungi@0.2.0-BETA+1.17.1
	- magna@1.5.5-1.17-pre4
	- mavm@1.0.4
	- maybe-data@1.0.1-1.17
	- me_hypherionmc_simple-rpc-lib@2.1.5
	- megane@5.2.1
	- megane-base@5.2.1
	- megane-fabric-transfer@5.2.1+1.1.0-3fe74aa118
	- megane-runtime@5.2.1
	- megane-vanilla@5.2.1+1.17.1
	- minecraft@1.17.1
	- mining_dims@1.1.12
	- mm@2.3
	- mob_catcher@1.0.10
	- modmenu@2.0.9
	- more-structures-add-on-for-william-wythers-overhauled-overworld@1.2
	- morerespawnanchors@1.0.2
	- morevillagers-fabric@2.0.4-SNAPSHOT
	- mostructures@1.3.0-pre1-1.17.1
	- mousewheelie@1.7.3+mc1.17.1-pre1
	- multi_item_lib@1.4.0
	- mythic-mounts@1.17.1-1.2
	- namepain@1.4.0
	- naturescompass@1.17.1-2.0.1-fabric
	- nears@1.1.2
	- nearsightedly@1.2.1
	- net_auoeke_shortcode@0.4.1
	- net_gudenau_lib_unsafe@1.4.3
	- net_objecthunter_exp4j@0.4.8
	- netherite_items@1.1.0
	- neutrino@0.0.9
	- no_fog@1.1.0+1.17.1
	- notenoughanimations@1.3.0
	- notenoughcrashes@3.4.4+1.17
	- npcvariety@2.1.2
	- omega-config@1.0.8
	- onsoulfire@1.17-3
	- openloader@3.0.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- org_slf4j_slf4j-api@1.7.29
	- org_yaml_snakeyaml@1.27
	- outvoted@2.0.0-alpha.12
	- owo@0.1.1
	- oxidized@1.3.0
	- oxidizelib@1.1.0
	- packet_tweaker@0.2.0-1.17-pre1
	- patchouli@1.17-54-FABRIC
	- paxi@1.17-1.2.2
	- pehkui@2.3.0+1.14.4-1.17.1
	- pigsteel@1.6.6
	- placeholder-api@1.1.0+1.17.1
	- playerabilitylib@1.3.0
	- playerex@3.0.1
	- polymer@0.1.0-rc.4+1.17.1
	- polymorph@0.0.12-1.17.1
	- presencefootsteps@r32-1.17-rc1
	- primordial-shores-add-on-for-wwoo@1.0
	- promenade@2.1.2
	- pugh_lib@${version}
	- pugh_tools@${version}
	- quartzelv@1.2.5
	- quickshulker@1.2.2-1.17
	- rangers_haven@2.3.1
	- ratsmischief@1.2.2
	- reach-entity-attributes@2.1.1
	- realisticfirespread@1.17-3
	- reapingmod@1.4.1
	- reeses-sodium-options@1.2.0
	- repurposed_structures@2.3.3+1.17.1
	- rhino@1605.1.2-build.40
	- roughlyenoughitems@6.0.279-alpha
	- rpgdifficulty@1.0.7
	- rpgstats@4.1.8+1.17.1
	- runelic@3.0.1
	- satin@1.6.1
	- scorch@1.1.0
	- seasons@1.2.2-BETA+1.17
	- seedy-behavior@1.0.1
	- server_translations_api@1.4.5+1.17
	- sgui@1.0.0-rc4+1.17.1
	- shulkerutils@1.0.4-1.17
	- simple-rpc@1.17-2.3.1-fabric
	- sit@1.17.1-13
	- smootherbedrock@1.0.2
	- snowundertrees@1.0.0
	- sodium@0.3.2+build.7
	- sodium-extra@0.3.4
	- somnus@0.0.14-1.17.1
	- spark@1.6.1
	- spawnermod@1.1.2
	- spellbound@1.4.0
	- spirit@1.1.0
	- stacc@1.3.0
	- stacker@2.0.0
	- staffofbuilding@1.3.2-1.17
	- starlight@1.0.0+fabric.73f6d37
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- step-height-entity-attribute@1.0.0
	- stoneholm@1.3
	- stonevaults@1.1.0
	- sulfurpotassiummod@1.1.1
	- talking-villagers@1.1.3
	- terraform-biome-builder-api-v1@2.0.0
	- terraform-config-api-v1@2.0.0
	- terraform-overworld-biome-extensions-api-v1@2.0.0
	- terraform-shapes-api-v1@1.0.4
	- terraform-surfaces-api-v1@2.0.0
	- terraform-tree-api-v1@2.0.0
	- terraform-wood-api-v1@2.0.2
	- the_aether@1.17.1-1.5.0
	- things@0.2.5
	- totemicoverhaul@1.1.7
	- transliterationlib@1.1.0
	- traverse@4.0.0-beta.2
	- trinketofundying@2.0.0-1.17
	- trinkets@3.0.4
	- trinketshulkerboxes@2.0.0-1.17
	- tweed@3.0.0-beta.26
	- universal-graves@1.0.8+1.17.1
	- upgradedechests@1.0.2-1.17
	- upgradedshulkers@1.0.2-1.17
	- urns@1.0.1
	- user11681_reflect@2.0.0
	- vanilla-hammers@3.1.2-1.17
	- vanilla_degus@1.2.0
	- vanillaexcavators@1.1.0
	- veinmining@0.0.10-1.17
	- villagernames@2.0.0
	- villagershats@1.2.0
	- voidtotem@1.17.0-1.0.0
	- voidz@1.0.5
	- wandering_collector@1.0.2+mc1.17
	- ward_blocks@1.1.8
	- waystones@2.0.4
	- william-wythers-overhauled-overworld@1.6
	- wolveswitharmor@1.6.0-1.17
	- woods_and_mires@1.1.1+1.17
	- wrenchable@1.1.0+1.17
	- wthit@3.8.1
	- xaerominimap@21.16.0
	- xaeroworldmap@1.16.1
	- xps@0.1.9_for_1.17.x_Fabric
	- yungsapi@1.17-Fabric-16
[14:39:05] [main/WARN]: Mod `assembly` (21w06a-1.0.0) does not respect SemVer - comparison support is limited.
[14:39:05] [main/WARN]: Mod `xps` (0.1.9_for_1.17.x_Fabric) does not respect SemVer - comparison support is limited.
[14:39:05] [main/WARN]: Mod `pugh_lib` (${version}) does not respect SemVer - comparison support is limited.
[14:39:05] [main/WARN]: Mod `pugh_tools` (${version}) does not respect SemVer - comparison support is limited.
[14:39:05] [main/WARN]: Mod `clumps` (fabric-1.17.1-7.0.5) does not respect SemVer - comparison support is limited.
[14:39:05] [main/WARN]: Mod `presencefootsteps` (r32-1.17-rc1) does not respect SemVer - comparison support is limited.

**Comment by auoeke** [comment]
I don't see anything fatally wrong here; and there's much more than just Fabric API. Your launcher's log might contain more information: https://files.auoeke.net/minecraft/log.

**Comment by MysteriousDownloader** [comment]
If it works for u then I might have to fresh install everything. It still keeps crashing even with Limitless and Fabric API (0.39 and 0.40) alone in the mods folder. Ty for also fixing Levelz Issue.
