### ISSUE TITLE
[BUG] Crash after reconfigure

### ISSUE THREAD

**Issue by Kronon-Conspirator** [auoeke/limitless#52]
fabric API : 0.40.1
version : 1.5.4
modlist : should be inlcuded in the log

currently setting up my modpack, reconfigure most of the max level to global(10) or just change value to 10.
1. changed setting json file in txt file before launch, result ~~fail~~ crash.
2. changed setting in game with the cloth config > main menu loads fine > generating world result crash

[2021-09-11-7.log.gz](https://github.com/auoeke/limitless/files/7145654/2021-09-11-7.log.gz)

**Comment by auoeke** [comment]
> changed setting json file in txt file before launch, result fail

What does "fail" mean? A crash?

The log does not show anything particularly wrong with limitless. Could you post your launcher's entire log?

**Comment by Kronon-Conspirator** [comment]
sorry those were the outputs from the vanilla launcher, the new one is from MultiMC, should have a better output.
[log.txt](https://github.com/auoeke/limitless/files/7145982/log.txt)
