### ISSUE TITLE
game crashes upon attempting to start world

### ISSUE THREAD

**Issue by cheezkid26** [auoeke/limitless#55]
The game loads just fine, but upon starting a world, it breaks. I don't understand what any of the error messages or anything mean, so I'm not sure what's wrong with the game, whether there be conflicting mods or if limitless is just broken or something. Here's the error log.
[crash-2021-09-19-15.26.24.txt](https://github.com/auoeke/limitless/files/7192787/crash-2021-09-19-15.26.24.txt)

**Comment by auoeke** [comment]
It appears to be caused by Immersive Portals.

**Comment by cheezkid26** [comment]
Removing Immersive Portals worked. Thanks.
