### ISSUE TITLE
Crash on startup only on servers [1.17.1]

### ISSUE THREAD

**Issue by shinjitumala** [auoeke/limitless#59]
Hi. I'm having trouble using this mod in a 1.17.1 server. The server crashes during startup when using this mod.

Removing "limitless" allows the server to start, but I am not sure if it is an incompatibility with other mods or a bug.

The game starts fine with "limitless" when run from the client side. And the code seems to be crashing in a validation method. So, I suspect it's a bug.

[latest.log](https://github.com/auoeke/limitless/files/7439636/latest.log)

**Comment by auoeke** [comment]
I believe that this issue is fixed in the latest version.
