### ISSUE TITLE
Installing this MOD together with betterend will cause the game to fail to start

### ISSUE THREAD

**Issue by NaiHeKK** [auoeke/limitless#62]
Hi. I'm having trouble using this mod in a 1.17.1 client.When I enable MOD and betterend at the same time, the game will not start.
The following is the error log at startup.
[latest.log](https://github.com/auoeke/limitless/files/7467210/latest.log)

**Comment by Metal-666** [comment]
Same issue here

**Comment by auoeke** [comment]
I believe that this issue has been fixed a while ago so I'll close it now.
