### ISSUE TITLE
Crashes when generating world (Version: 1.18.1)

### ISSUE THREAD

**Issue by EH099** [auoeke/limitless#70]
Minecraft version: 1.18.1
Fabric API version: 0.45.0
Fabric Loader version: 0.12.12
Limitless version: 1.6.2
Crash log: [minecraft-exported-logs-2022-01-08T22-49-44.log](https://github.com/auoeke/limitless/files/7833420/minecraft-exported-logs-2022-01-08T22-49-44.log)
I've tried to delete _bclib_ and the _better mods_ once but it doesn't work and keeps crashing. The game crashes when **generating the world**, not starting the game.

**Comment by auoeke** [comment]
I don't see anything that indicates a crash—the log is just cut off after a freeze—so there's little for me to go on. I can only guess that a mod tries to generate some items or something for each enchantment level (likely more than 2 billion for each enchantment); though in that case an error stating that the Java virtual machine ran out of memory should be thrown but I don't see anything like that.

**Comment by EH099** [comment]
It was my fault. I installed _limitless_ with [_enchantment descirptions_](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions?__cf_chl_captcha_tk__=oprS2iEmzhzZye6wCqz.ERZ7rjSw2hQ_ejYn9mw9aWE-1641739199-0-gaNycGzNDj0) (Version: 9.0.8) together and so they crashed. Now I removes _enchantment descriptions_ from the game and the world generates successfully.
