### ISSUE TITLE
[QUILTMC] Crash while loading

### ISSUE THREAD

**Issue by ExoPlant** [auoeke/limitless#80]
Limitless seems to crash because it relies on a mixin plugin that fails to load on Quilt, with ExceptionInInitializerError:null.

For reference, here's a crash log: https://mclo.gs/HsNhpFJ

**Comment by auoeke** [comment]
The explicit dependency on `fabricloader` ought to have prevented Quilt Loader from trying to load limitless by indicating that limitless depends spcifically on Fabric Loader; but this news is good nonetheless. After investigating a little, I've concluded that limitless is incompatible with Quilt Loader in more ways than what this exception suggests. I've added disclaimers related to Quilt to this repository and this mod's page on Modrinth.

**Comment by ExoPlant** [comment]
> The explicit dependency on `fabricloader` ought to have prevented Quilt Loader from trying to load limitless by indicating that limitless depends spcifically on Fabric Loader; but this news is good nonetheless. After investigating a little, I've concluded that limitless is incompatible with Quilt Loader in more ways than what this exception suggests. I've added disclaimers related to Quilt to this repository and this mod's page on Modrinth.

Quilt ignores that dependency, as it aims to be compatible with Fabric mods, however some do not work on Quilt
