### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Zolyn** [auoeke/limitless#81]
Mod version: 1.6.7
Fabric API:  0.59.0
Java version: 17.0.4.101-hotspot
[Crash log](https://pastebin.com/aG2nEPpg)

**Comment by auoeke** [comment]
Use Fabric Loader 0.12-0.13.3. I've published a new version with better version constraints at <https://modrinth.com/mod/limitless/version/1.6.7-1>.
